// carData module

const carsForSale = [
    {
        id: 1,
        make: "Toyota",
        model: "Camry",
        year: 2018,
        price: 15000,
        mileage: 40000,
        color: "Silver",
        seller: {
            name: "John Doe",
            contact: "john@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 2,
        make: "Honda",
        model: "Civic",
        year: 2017,
        price: 13000,
        mileage: 35000,
        color: "Blue",
        seller: {
            name: "Jane Smith",
            contact: "jane@example.com",
        },
        features: [
            "Manual Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 3,
        make: "Ford",
        model: "Escape",
        year: 2019,
        price: 18000,
        mileage: 30000,
        color: "Black",
        seller: {
            name: "Bob Johnson",
            contact: "bob@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 4,
        make: "Chevrolet",
        model: "Malibu",
        year: 2017,
        price: 12000,
        mileage: 42000,
        color: "White",
        seller: {
            name: "Mike Adams",
            contact: "mike@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 5,
        make: "Honda",
        model: "Accord",
        year: 2019,
        price: 19000,
        mileage: 28000,
        color: "Silver",
        seller: {
            name: "Emily Brown",
            contact: "emily@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Sunroof",
        ],
    },
    {
        id: 6,
        make: "Ford",
        model: "Explorer",
        year: 2017,
        price: 15000,
        mileage: 32000,
        color: "Blue",
        seller: {
            name: "Chris Johnson",
            contact: "chris@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 7,
        make: "Toyota",
        model: "Corolla",
        year: 2020,
        price: 16000,
        mileage: 22000,
        color: "Gray",
        seller: {
            name: "Lisa Davis",
            contact: "lisa@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 8,
        make: "Chevrolet",
        model: "Impala",
        year: 2018,
        price: 14000,
        mileage: 39000,
        color: "Black",
        seller: {
            name: "David Wilson",
            contact: "david@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 9,
        make: "Honda",
        model: "Civic",
        year: 2019,
        price: 16000,
        mileage: 26000,
        color: "Silver",
        seller: {
            name: "Amanda Johnson",
            contact: "amanda@example.com",
        },
        features: [
            "Manual Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 10,
        make: "Toyota",
        model: "Corolla",
        year: 2017,
        price: 13000,
        mileage: 34000,
        color: "White",
        seller: {
            name: "Daniel Clark",
            contact: "daniel@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 11,
        make: "Ford",
        model: "Explorer",
        year: 2018,
        price: 22000,
        mileage: 28000,
        color: "Red",
        seller: {
            name: "Linda Evans",
            contact: "linda@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 12,
        make: "Chevrolet",
        model: "Impala",
        year: 2017,
        price: 14000,
        mileage: 38000,
        color: "Blue",
        seller: {
            name: "Mark Taylor",
            contact: "mark@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 13,
        make: "Honda",
        model: "Accord",
        year: 2020,
        price: 21000,
        mileage: 24000,
        color: "Black",
        seller: {
            name: "Maria Garcia",
            contact: "maria@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Sunroof",
        ],
    },
    {
        id: 14,
        make: "Toyota",
        model: "Camry",
        year: 2017,
        price: 14000,
        mileage: 36000,
        color: "Green",
        seller: {
            name: "Tom Wilson",
            contact: "tom@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 15,
        make: "Ford",
        model: "Explorer",
        year: 2019,
        price: 24000,
        mileage: 22000,
        color: "Silver",
        seller: {
            name: "Susan Adams",
            contact: "susan@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 16,
        make: "Chevrolet",
        model: "Malibu",
        year: 2019,
        price: 16000,
        mileage: 30000,
        color: "Red",
        seller: {
            name: "Robert Brown",
            contact: "robert@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 17,
        make: "Honda",
        model: "Civic",
        year: 2018,
        price: 15000,
        mileage: 33000,
        color: "White",
        seller: {
            name: "Karen Davis",
            contact: "karen@example.com",
        },
        features: [
            "Manual Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 18,
        make: "Toyota",
        model: "Corolla",
        year: 2018,
        price: 14000,
        mileage: 32000,
        color: "Blue",
        seller: {
            name: "Michael Johnson",
            contact: "michael@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 19,
        make: "Toyota",
        model: "Camry",
        year: 2018,
        price: 15500,
        mileage: 39000,
        color: "Silver",
        seller: {
            name: "David Taylor",
            contact: "david@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 20,
        make: "Honda",
        model: "Civic",
        year: 2020,
        price: 17500,
        mileage: 26000,
        color: "Black",
        seller: {
            name: "Eva White",
            contact: "eva@example.com",
        },
        features: [
            "Manual Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 21,
        make: "Chevrolet",
        model: "Malibu",
        year: 2021,
        price: 22000,
        mileage: 18000,
        color: "White",
        seller: {
            name: "Sophia Davis",
            contact: "sophia@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 22,
        make: "Nissan",
        model: "Altima",
        year: 2020,
        price: 19000,
        mileage: 22000,
        color: "Black",
        seller: {
            name: "Oliver Smith",
            contact: "oliver@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 23,
        make: "Jeep",
        model: "Wrangler",
        year: 2020,
        price: 27000,
        mileage: 15000,
        color: "Red",
        seller: {
            name: "Sophie Adams",
            contact: "sophie@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 24,
        make: "Kia",
        model: "Soul",
        year: 2019,
        price: 15500,
        mileage: 27000,
        color: "Blue",
        seller: {
            name: "William Davis",
            contact: "william@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 25,
        make: "Subaru",
        model: "Outback",
        year: 2021,
        price: 25000,
        mileage: 17000,
        color: "White",
        seller: {
            name: "Lucas Johnson",
            contact: "lucas@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 26,
        make: "GMC",
        model: "Sierra",
        year: 2020,
        price: 35000,
        mileage: 12000,
        color: "Black",
        seller: {
            name: "Ethan Wilson",
            contact: "ethan@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 27,
        make: "Mazda",
        model: "CX-5",
        year: 2019,
        price: 22000,
        mileage: 19000,
        color: "Red",
        seller: {
            name: "Alex Johnson",
            contact: "alex@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 28,
        make: "Hyundai",
        model: "Tucson",
        year: 2020,
        price: 18000,
        mileage: 23000,
        color: "Gray",
        seller: {
            name: "Noah Davis",
            contact: "noah@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 29,
        make: "Audi",
        model: "A4",
        year: 2021,
        price: 34000,
        mileage: 15000,
        color: "Blue",
        seller: {
            name: "Sophie Johnson",
            contact: "sophie@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Sunroof",
        ],
    },
    {
        id: 30,
        make: "BMW",
        model: "3 Series",
        year: 2020,
        price: 32000,
        mileage: 16000,
        color: "White",
        seller: {
            name: "Lily Smith",
            contact: "lily@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 31,
        make: "Mercedes-Benz",
        model: "C-Class",
        year: 2021,
        price: 38000,
        mileage: 13000,
        color: "Black",
        seller: {
            name: "James Wilson",
            contact: "james@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 32,
        make: "Lexus",
        model: "RX",
        year: 2020,
        price: 37000,
        mileage: 14000,
        color: "Silver",
        seller: {
            name: "Aiden Johnson",
            contact: "aiden@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 33,
        make: "Tesla",
        model: "Model 3",
        year: 2020,
        price: 42000,
        mileage: 11000,
        color: "Red",
        seller: {
            name: "Olivia Smith",
            contact: "olivia@example.com",
        },
        features: [
            "Automatic Transmission",
            "Electric",
            "Autopilot",
            "Navigation System",
        ],
    },
    {
        id: 34,
        make: "Porsche",
        model: "911",
        year: 2021,
        price: 150000,
        mileage: 5000,
        color: "Blue",
        seller: {
            name: "Chloe Adams",
            contact: "chloe@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 35,
        make: "Jaguar",
        model: "F-PACE",
        year: 2020,
        price: 48000,
        mileage: 9000,
        color: "Green",
        seller: {
            name: "Ethan Smith",
            contact: "ethan@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 36,
        make: "Subaru",
        model: "Forester",
        year: 2019,
        price: 25000,
        mileage: 18000,
        color: "Gray",
        seller: {
            name: "Olivia Johnson",
            contact: "olivia@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 37,
        make: "Mazda",
        model: "Mazda3",
        year: 2019,
        price: 20000,
        mileage: 22000,
        color: "Black",
        seller: {
            name: "Lucas Davis",
            contact: "lucas@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 38,
        make: "Nissan",
        model: "Maxima",
        year: 2020,
        price: 28000,
        mileage: 14000,
        color: "White",
        seller: {
            name: "Ella Johnson",
            contact: "ella@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 39,
        make: "Hyundai",
        model: "Sonata",
        year: 2020,
        price: 19000,
        mileage: 21000,
        color: "Blue",
        seller: {
            name: "Matthew Wilson",
            contact: "matthew@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 40,
        make: "Kia",
        model: "Optima",
        year: 2021,
        price: 20000,
        mileage: 18000,
        color: "Silver",
        seller: {
            name: "Sophie Johnson",
            contact: "sophie@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
            "Sunroof",
        ],
    },
    {
        id: 41,
        make: "BMW",
        model: "5 Series",
        year: 2020,
        price: 30000,
        mileage: 16000,
        color: "Black",
        seller: {
            name: "Noah Davis",
            contact: "noah@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 42,
        make: "Lexus",
        model: "IS",
        year: 2021,
        price: 35000,
        mileage: 13000,
        color: "Gray",
        seller: {
            name: "Sophie Adams",
            contact: "sophie@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 43,
        make: "Tesla",
        model: "Model S",
        year: 2021,
        price: 70000,
        mileage: 9000,
        color: "White",
        seller: {
            name: "Oliver Smith",
            contact: "oliver@example.com",
        },
        features: [
            "Automatic Transmission",
            "Electric",
            "Autopilot",
            "Navigation System",
            "Panoramic Roof",
        ],
    },
    {
        id: 44,
        make: "Porsche",
        model: "Panamera",
        year: 2020,
        price: 80000,
        mileage: 12000,
        color: "Red",
        seller: {
            name: "Chloe Adams",
            contact: "chloe@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 45,
        make: "Jaguar",
        model: "XE",
        year: 2021,
        price: 55000,
        mileage: 8000,
        color: "Black",
        seller: {
            name: "Ethan Smith",
            contact: "ethan@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 46,
        make: "Subaru",
        model: "Crosstrek",
        year: 2020,
        price: 27000,
        mileage: 15000,
        color: "Blue",
        seller: {
            name: "Olivia Johnson",
            contact: "olivia@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
        ],
    },
    {
        id: 47,
        make: "Mazda",
        model: "CX-9",
        year: 2021,
        price: 34000,
        mileage: 12000,
        color: "White",
        seller: {
            name: "Lucas Davis",
            contact: "lucas@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 48,
        make: "Nissan",
        model: "Rogue",
        year: 2020,
        price: 24000,
        mileage: 19000,
        color: "Gray",
        seller: {
            name: "Ella Johnson",
            contact: "ella@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Windows",
            "Air Conditioning",
            "Cruise Control",
            "Keyless Entry",
            "Navigation System",
        ],
    },
    {
        id: 49,
        make: "Hyundai",
        model: "Elantra",
        year: 2020,
        price: 18000,
        mileage: 21000,
        color: "Red",
        seller: {
            name: "Matthew Wilson",
            contact: "matthew@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
        ],
    },
    {
        id: 50,
        make: "Kia",
        model: "Forte",
        year: 2021,
        price: 20000,
        mileage: 18000,
        color: "Silver",
        seller: {
            name: "Sophie Johnson",
            contact: "sophie@example.com",
        },
        features: [
            "Automatic Transmission",
            "Power Locks",
            "Air Conditioning",
            "Bluetooth",
            "Backup Camera",
            "Sunroof",
        ],
    },
]

// export the carsForSale array from this module
// for use in other parts of the applicati  on
module.exports = { carsForSale }
